name: Build NEON STRIKE APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: NEON_STRIKE

jobs:
  android:
    name: Android APK
    runs-on: ubuntu-24.04

    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Preparar Godot
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mkdir -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Comprobar proyecto
        run: |
          godot --version
          echo "Contenido del proyecto:"
          ls -la
          echo "Export presets:"
          cat export_presets.cfg

      - name: Exportar APK
        run: |
          mkdir -p build/android
          godot --headless --verbose --export-release "Android" "build/android/${EXPORT_NAME}.apk"

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: NEON_STRIKE-Android
          path: build/android/NEON_STRIKE.apk
          if-no-files-found: error
