name: Build NEON STRIKE APK

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  android:
    name: Android APK
    runs-on: ubuntu-24.04

    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Comprobar proyecto
        run: |
          cd NEON_STRIKE_V3_APK_READY
          godot --version
          echo "Proyecto:"
          ls -la
          echo "Export presets:"
          ls -la export_presets.cfg

      - name: Exportar APK
        run: |
          cd NEON_STRIKE_V3_APK_READY
          mkdir -p build/android
          godot --headless --verbose --export-release "Android" build/android/NEON_STRIKE.apk

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: NEON_STRIKE-Android
          path: NEON_STRIKE_V3_APK_READY/build/android/NEON_STRIKE.apk
          if-no-files-found: error
